name: Scheduled Node Dependencies Update (npm)
on:
  schedule:
    - cron:  '0 15 1 * *'
  workflow_dispatch:
jobs:
  update-deps:
    name: Update Node dependencies using npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-node-update-deps@0cba95f3d07e4a92741250d4aa1e3c23be5e8b4c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request-labels: 'a,b'
